services:
  api:
    image: henriqueamrl/tecnologias-sustentaveis-backend:latest
    environment:
      MYSQL_HOST: bd
    ports:
      - "3000:3000"
    depends_on:
      - bd
  bd:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      LANG: C.UTF-8
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./api/docs/bd:/docker-entrypoint-initdb.d
      - dados-bd:/var/lib/mysql
    ports:
      - "3306:3306"
  frontend:
    image: henriqueamrl/tecnologias-sustentaveis-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - api
volumes:
  dados-bd: